
<div class="cat-des-wrapper">
    <div class="left">
        <div class="des">
            <h2 class="title">REDUCE CHASSIS &amp; BODY FLEX</h2>
            <p class="text">Whiteline strut bars / strut brace / strut tower bars not only make your vehicle handle better, they look great on the car as they feature premium polished alloy materials and powder coated end brackets.</p>
        </div>
    </div>
    <div class="right"><img src="{{media url="wysiwyg/whiteline-media/featured-bracing.png"}}" alt="bracing" /></div>
</div>
